spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/verifyme
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081